[SA-1744] Added documentation for new metrics
SparkPost/developers.sparkpost.com pull request #425
Opened 2020-12-16 18:37 UTC by comikal268

2020-12-16 20:46 UTC, gwalls requested changes
We should create a "Deliverability" tag similar to the "Enterprise" tag. We'll be able to use that in the new deliverability metrics descriptions (as well as the new routes and filter terms in the future).
![image](https://user-images.githubusercontent.com/8743712/102404373-a1bbc500-3fb5-11eb-9c80-b38ce3689ed2.png)


I'm a little worried about overloading the term "deliverability" within our API docs. We already use that term in the numerous `metrics/deliverability/` routes. But that's ultimately product's call.

The new metric descriptions make sense to me, but @haleysolomon should probably sign off on them too.

2020-12-16 20:46 UTC, gwalls commented on content/api/metrics.apib
> + and `count_moved_to_spam` are only available to the SparkPost Deliverability customers only.
Use the Deliverability tag, similar to the Enterprise tag

2020-12-16 20:46 UTC, gwalls commented on content/api/metrics.apib
> +| `count_inbox_panel`              | Panel messages delivered to the inbox.                                                              |
Prefix the descriptions with the Deliverability tag (should link to the product page or wherever @haleysolomon thinks it should redirect to)

2020-12-17 16:31 UTC, gwalls approved these changes
lgtm

2021-02-16 15:57 UTC, mvanbosch approved these changes
lgtm

2021-02-17 15:52 UTC, merged